# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://tijeco.github.io/classify_peptides/"

git_url = "https://github.com/tijeco/classify_peptides/tree/{branch}/"

def custom_doc_links(name): return None
